# All the CI config is in the library-utils repo
#
# The goal is to have only one place where all the CI
# related things are.
include:
  - remote: 'https://gitlab.com/ulikoehler/kicad-library-utils/-/raw/testing-kicad-cli/tools/gitlabci/gitlab-ci-symbols.yml'
